### ISSUE TITLE
Generalize functional/pathway analysis scripts

### ISSUE THREAD

**Issue by khughitt** [NCBI-Hackathons/Pharmacogenomics_Prediction_Pipeline_P3#10]
Currently, there are several scripts which perform very similar tasks on different gene/annotation mappings:
go_term_analysis.R, variant_go_term_analysis.R, cpdb_pathway_analysis.R, etc.

The main functionality of the scripts should be abstracted into generic functions that are capable on working on various types of data and annotation mappings.

**Comment by daler** [comment]
This is actually done already (at least in the redo-pipeline branch): see [README_pivot.rst](https://github.com/DCGenomics/Pharmacogenomics_Prediction_Pipeline_P3/blob/redo-pipeline/README_pivot.rst) and the implementation in [pipeline_helpers.py](https://github.com/DCGenomics/Pharmacogenomics_Prediction_Pipeline_P3/blob/redo-pipeline/tools/pipeline_helpers.py)

**Comment by khughitt** [comment]
Ha! I should just start assigning all of the issues to you since you appear to have taken care of everything.

Nice work.

**Comment by daler** [comment]
I just lucked out and had some time on the weekend!
