### ISSUE TITLE
proposal: work on branches from main repo rather than forks

### ISSUE THREAD

**Issue by daler** [NCBI-Hackathons/Pharmacogenomics_Prediction_Pipeline_P3#24]
It looks like we'll be using a development model where we have new features (new viz tools, new downstream analysis, etc) as a pull request that then need to get integrated into the pipeline. That means the current workflow to test a PR is:
- checkout a new branch in my own fork
- pull the changes from the PR to be checked
- make any changes to get things running
- commit those changes to the branch on my own (or on clone of original repo)
- submit the combination of original PR and the additional changes as another PR
- merge that combined PR into master

In my experience (and as discussed [here](http://codeinthehole.com/writing/pull-requests-and-other-good-practices-for-teams-using-github/)), for small teams like us where members all have developer access, it's a lot easier to work on branches off the main repo rather than a fork. That way, the workflow becomes:
- checkout the feature branch
- make any changes to get things running
- push changes directly to the feature branch
- merge when ready

Extra benefits: discussion and any relevant commits show up on the same PR page, and anyone can push changes to the branch to get it working.

So I propose we each clone the main repo and create feature branches for our work to be submitted as a PR, rather than forking to our own accounts.

Thoughts?

**Comment by khughitt** [comment]
Whoops! Missed this entirely. will try and remember to do this going forward. Thanks!

**Comment by khughitt** [comment]
Closing issue. I'm going to try and do all future dev on branches of the main repo.
